import "../globals.css";
import { cookies } from "next/headers";
import { redirect } from "next/navigation";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const token = await cookies();
  const myToken = token.get("accessToken")?.value;

  if (!myToken) {
    return redirect("/login");
  }
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
